In [87]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [88]:
df = sns.load_dataset('iris')

In [89]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [90]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
x = df.drop('species',axis=1)
y = df['species']

In [93]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [94]:
from sklearn.neighbors import KNeighborsClassifier

In [95]:
model_knn = KNeighborsClassifier(n_neighbors=17)

In [96]:
model_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [97]:
model_knn.score(x_test,y_test)

1.0

In [98]:
from sklearn.svm import SVC

In [99]:
model_svm = SVC(gamma='auto')

In [100]:
model_svm.fit(x_train,y_train)

SVC(gamma='auto')

In [101]:
model_svm.score(x_train,y_train)

0.98

#NoW leatest Use the Grid Search CV

In [102]:
from sklearn.model_selection import GridSearchCV

In [103]:
classifire = GridSearchCV(model_svm, { 
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
}, cv=5, return_train_score=False)

In [104]:
classifire.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [105]:
classifire.cv_results_

{'mean_fit_time': array([0.00244322, 0.00138192, 0.00090079, 0.00044436, 0.00056047,
        0.00055857, 0.00053496, 0.00048103]),
 'std_fit_time': array([1.16740528e-03, 5.37807832e-04, 3.75534205e-04, 1.33253592e-05,
        5.90622831e-05, 3.59154938e-05, 4.09784321e-05, 2.42895063e-05]),
 'mean_score_time': array([0.0030705 , 0.00088944, 0.00077009, 0.00031791, 0.00039401,
        0.00039415, 0.00039005, 0.00034022]),
 'std_score_time': array([2.08028441e-03, 3.95629626e-04, 5.05983613e-04, 4.67835334e-06,
        4.77389016e-05, 3.92276168e-05, 7.91463503e-06, 2.01228671e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [106]:
results = pd.DataFrame(classifire.cv_results_)

In [107]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002443,0.001167,0.003070,0.002080,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.001382,0.000538,0.000889,0.000396,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000901,0.000376,0.000770,0.000506,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000444,0.000013,0.000318,0.000005,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000560,0.000059,0.000394,0.000048,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000559,0.000036,0.000394,0.000039,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.000535,0.000041,0.000390,0.000008,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.000481,0.000024,0.000340,0.000020,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [108]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [109]:
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['minkowski', 'euclidean']
}

In [110]:
classifire_knn = GridSearchCV(model_knn, param_grid, cv=5, return_train_score=False)

In [111]:
classifire_knn.fit(x, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=17),
             param_grid={'metric': ['minkowski', 'euclidean'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']})

In [112]:
results_knn = pd.DataFrame(classifire_knn.cv_results_)

In [113]:
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001984,0.000196,0.002875,0.000624,minkowski,3,uniform,"{'metric': 'minkowski', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,15
1,0.000820,0.000114,0.001091,0.000172,minkowski,3,distance,"{'metric': 'minkowski', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,15
2,0.000750,0.000104,0.001055,0.000189,minkowski,5,uniform,"{'metric': 'minkowski', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
3,0.000583,0.000020,0.000768,0.000130,minkowski,5,distance,"{'metric': 'minkowski', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,15
4,0.000531,0.000027,0.000811,0.000046,minkowski,7,uniform,"{'metric': 'minkowski', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
5,0.000495,0.000016,0.000572,0.000023,minkowski,7,distance,"{'metric': 'minkowski', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
6,0.000465,0.000018,0.000720,0.000053,minkowski,9,uniform,"{'metric': 'minkowski', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,9
7,0.000450,0.000054,0.000519,0.000049,minkowski,9,distance,"{'metric': 'minkowski', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
8,0.000517,0.000214,0.000675,0.000057,minkowski,11,uniform,"{'metric': 'minkowski', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,3
9,0.000452,0.000080,0.000505,0.000066,minkowski,11,distance,"{'metric': 'minkowski', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
10,0.000356,0.000012,0.000549,0.000038,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,15
11,0.000331,0.000012,0.000377,0.000015,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,15
12,0.000343,0.000036,0.000492,0.000013,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
13,0.000323,0.000002,0.000376,0.000007,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,15
14,0.000328,0.000009,0.000485,0.000005,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
15,0.000328,0.000006,0.000380,0.000007,euclidean,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,3
16,0.000332,0.000009,0.000487,0.000005,euclidean,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.966667,0.933333,1.0,0.973333,0.024944,9
17,0.000371,0.000056,0.000486,0.000086,euclidean,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
18,0.000313,0.000002,0.000494,0.000015,euclidean,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.933333,1.000000,1.000000,0.966667,1.0,0.980000,0.026667,3
19,0.000331,0.000030,0.000384,0.000011,euclidean,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1

In [114]:
print(results_knn[['param_n_neighbors', 'param_weights', 'mean_test_score']])

    param_n_neighbors param_weights  mean_test_score
0                   3       uniform         0.966667
1                   3      distance         0.966667
2                   5       uniform         0.973333
3                   5      distance         0.966667
4                   7       uniform         0.980000
5                   7      distance         0.980000
6                   9       uniform         0.973333
7                   9      distance         0.973333
8                  11       uniform         0.980000
9                  11      distance         0.986667
10                  3       uniform         0.966667
11                  3      distance         0.966667
12                  5       uniform         0.973333
13                  5      distance         0.966667
14                  7       uniform         0.980000
15                  7      distance         0.980000
16                  9       uniform         0.973333
17                  9      distance         0.973333
18                 11       uniform         0.980000
19                 11      distance         0.986667

In [115]:
from sklearn.model_selection import RandomizedSearchCV

In [131]:
classifire_random = RandomizedSearchCV(model_svm, { 
    'C': [1,10,20,30],
    'kernel': ['rbf','linear'],
},n_iter=4, cv=5, return_train_score=False)

In [132]:
classifire_random.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [133]:
results = pd.DataFrame(classifire_random.cv_results_)

In [134]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1        1       linear         0.980000
2       30       linear         0.960000
3       10       linear         0.973333